### ISSUE TITLE
[Cache Optimization] - Backend Dynamic Caching

### ISSUE THREAD

**Issue by nikshepkulli-CTO** [starteryouInc/Starteryou-Website#75]
**Description**:
This ticket is to implement caching strategies for the following category of assets:

- **Paths**:
```plaintext

backend\routes\fileRoutes.js,
backend\routes\index.js,
backend\routes\textRoutes.js,


```

**Notes**: Cache optimization required for backend dynamic caching.

**Priority**: High
**Effort Estimate**: High
        

**[Feature] Implement MongoDB-Based Caching Strategy**

---

#### **Description:**
Implement a caching strategy for the project using **MongoDB** as the storage layer. This will optimize the performance of API calls, static asset serving, and data query operations. The caching strategy will cover the following categories:
1. **Frontend Static Assets**
2. **Frontend Dynamic Caching**
3. **Backend Static Assets**
4. **Backend Dynamic Caching**

---

#### **Tasks:**
1. **Setup MongoDB Cache Collection:**
   - Create a `cache` collection with the following schema:
     ```javascript
     {
       "key": "unique_cache_key",  // Unique identifier for the cached item
       "data": {...},             // Cached data (JSON, arrays, etc.)
       "createdAt": new Date(),   // Cache creation timestamp
       "expiresAt": new Date()    // Cache expiration timestamp
     }
     ```

2. **Implement Cache Middleware for Express APIs:**
   - Add a middleware for API routes to:
     - Check for existing cache in MongoDB.
     - Serve the cached response if available.
     - Save the response in MongoDB if not available, with an expiration time.

3. **Frontend Static Assets:**
   - Cache static files (e.g., CSS, JS, images) in MongoDB using GridFS.
   - Serve the assets via an Express route.

4. **Backend Dynamic Caching:**
   - Cache query results for frequently accessed database data in MongoDB.
   - Implement a helper function to manage cache:
     ```javascript
     const getCachedQueryResult = async (queryKey, queryFunction) => {
       const cachedResult = await Cache.findOne({ key: queryKey });
       if (cachedResult) {
         return cachedResult.data;
       }
       const freshResult = await queryFunction();
       await Cache.create({
         key: queryKey,
         data: freshResult,
         expiresAt: new Date(Date.now() + 1000 * 60 * 15) // Cache for 15 minutes
       });
       return freshResult;
     };
     ```

5. **Cache Invalidation:**
   - Use MongoDB TTL indexes for automatic expiration of cache entries:
     ```javascript
     db.cache.createIndex({ "expiresAt": 1 }, { expireAfterSeconds: 0 });
     ```
   - Set up manual or event-based invalidation for dynamic data.

6. **Analytics and Logging:**
   - Track cache hits and misses for analysis.
   - Log the following metrics:
     - Cache Key
     - Hit or Miss
     - Timestamp

---

#### **Acceptance Criteria:**
- [ ] MongoDB cache collection is created with TTL indexes.
- [ ] Middleware for API caching is functional and integrated.
- [ ] Frontend static assets are cached and served via MongoDB (GridFS).
- [ ] Backend query results are cached with proper expiration.
- [ ] Cache invalidation is implemented for dynamic data.
- [ ] Logs provide detailed metrics for cache performance.

### GitHub Task Template

**Title:** `[Feature] Implement In-Memory Caching Framework`

**Body:**

---

### Description

Implement an in-memory caching framework for the Express and MongoDB project. The caching should improve performance and reduce database load by storing frequently accessed data in memory. This implementation replaces Redis with a simpler `node-cache` solution.

---

### Tasks

1. **Install Dependencies**
   - Add `node-cache` to the project:
     ```bash
     npm install node-cache
     ```

2. **Setup Caching Logic**
   - Create a `cache` instance using `node-cache`.
   - Use `stdTTL` to set default expiration time (e.g., 10 minutes).
   - Use middleware to check the cache before querying the database.

3. **Implement Middleware**
   - Add a middleware function to handle cache hits and misses:
     - Check if data exists in the cache.
     - If found, return the cached response.
     - Otherwise, query the database and store the result in the cache.

4. **Add Cache Invalidation**
   - Invalidate relevant cache keys after data updates to ensure consistency.
   - Use `cache.flushAll()` for global cache invalidation.

5. **Integrate with Routes**
   - Apply the caching logic to API routes that fetch frequently accessed data.

6. **Optimize MongoDB Queries**
   - Add indexes to MongoDB collections for improved query performance:
     ```javascript
     mongoose.connection.once('open', () => {
         mongoose.connection.collection('collection_name').createIndex({ field_name: 1 });
     });
     ```

7. **Add HTTP Cache Control**
   - Use `Cache-Control` headers for static assets and API responses:
     ```javascript
     app.use((req, res, next) => {
         res.set('Cache-Control', 'public, max-age=600');
         next();
     });
     ```

8. **Testing**
   - Write unit tests to ensure:
     - Cache hits return correct data.
     - Cache misses query the database and update the cache.
   - Use tools like Postman or `curl` to manually test response times.

---

### Resources

- [[node-cache Documentation](https://www.npmjs.com/package/node-cache)](https://www.npmjs.com/package/node-cache)
- [[Express.js Official Docs](https://expressjs.com/)](https://expressjs.com/)
- [[Mongoose Official Docs](https://mongoosejs.com/)](https://mongoosejs.com/)

---
### Acceptance Criteria

- [ ] Cache middleware integrated and functional.
- [ ] Cache invalidation implemented on updates.
- [ ] MongoDB indexes created for optimized queries.
- [ ] Routes tested for both cache hits and misses.
