### ISSUE TITLE
[Cache Optimization] - Other

### ISSUE THREAD

**Issue by nikshepkulli-CTO** [starteryouInc/Starteryou-Website#76]
**Description**:
This ticket is to implement caching strategies for the following category of assets:

- **Paths**:
```plaintext
frontend\dockerfile,
frontend\docs\frontend\BetterFuture.jsx.html,
frontend\docs\frontend\fonts\OpenSans-Bold-webfont.eot,
frontend\docs\frontend\fonts\OpenSans-Bold-webfont.woff,
frontend\docs\frontend\fonts\OpenSans-BoldItalic-webfont.eot,
frontend\docs\frontend\fonts\OpenSans-BoldItalic-webfont.woff,
frontend\docs\frontend\fonts\OpenSans-Italic-webfont.eot,
frontend\docs\frontend\fonts\OpenSans-Italic-webfont.woff,
frontend\docs\frontend\fonts\OpenSans-Light-webfont.eot,
frontend\docs\frontend\fonts\OpenSans-Light-webfont.woff,
frontend\docs\frontend\fonts\OpenSans-LightItalic-webfont.eot,
frontend\docs\frontend\fonts\OpenSans-LightItalic-webfont.woff,
frontend\docs\frontend\fonts\OpenSans-Regular-webfont.eot,
frontend\docs\frontend\fonts\OpenSans-Regular-webfont.woff,
frontend\docs\frontend\global.html,
frontend\docs\frontend\HeroAbout.jsx.html,
frontend\docs\frontend\index.html,
frontend\docs\frontend\module-BetterFuture.html,
frontend\docs\frontend\module-OurVision.html,
frontend\docs\frontend\OurMission.jsx.html,
frontend\docs\frontend\OurVision.jsx.html,
frontend\docs\frontend\scripts\prettify\Apache-License-2.0.txt,
frontend\docs\frontend\Team.jsx.html,
frontend\docs\frontend\TechTeam.jsx.html,
frontend\index.html,
frontend\jsdoc.config.json,
frontend\nginx.conf,
frontend\package-lock.json,
frontend\package.json,
frontend\public\AboutPage\8471681-sd_640_338_25fps.mp4,
frontend\src\App.jsx,
frontend\src\components\About\BetterFuture.jsx,
frontend\src\components\About\HeroAbout.jsx,
frontend\src\components\About\OurMission.jsx,
frontend\src\components\About\OurVision.jsx,
frontend\src\components\About\Team.jsx,
frontend\src\components\About\TechTeam.jsx,
frontend\src\components\Auth\LoginPage.jsx,
frontend\src\components\Auth\Signup.jsx,
frontend\src\components\Common\AdminProtectedRoute.jsx,
frontend\src\components\Common\FileUpload.jsx,
frontend\src\components\Common\Footer.jsx,
frontend\src\components\Common\InProgressPage.jsx,
frontend\src\components\Common\Navbar.jsx,
frontend\src\components\Common\NewsLetter.jsx,
frontend\src\components\Education\ComprehensiveFeatures.jsx,
frontend\src\components\Education\EduHero.jsx,
frontend\src\components\Education\OurInsight.jsx,
frontend\src\components\Education\StartJourney.jsx,
frontend\src\components\Education\Testimonials.jsx,
frontend\src\components\Education\UnlockPotential.jsx,
frontend\src\components\Education\YourJourney.jsx,
frontend\src\components\Job\AfterSignup\CarrerOptions.jsx,
frontend\src\components\Job\AfterSignup\ExcitingCareer.jsx,
frontend\src\components\Job\AfterSignup\ExploreJob.jsx,
frontend\src\components\Job\AfterSignup\JobHero.jsx,
frontend\src\components\Job\AfterSignup\Reviews.jsx,
frontend\src\components\Job\BeforeSignup\DiscoverPath.jsx,
frontend\src\components\Job\BeforeSignup\HeroJobPortal.jsx,
frontend\src\components\Job\BeforeSignup\JobListing.jsx,
frontend\src\components\Job\BeforeSignup\LatestInsight.jsx,
frontend\src\components\Job\BeforeSignup\LaunchBanner.jsx,
frontend\src\components\Job\BeforeSignup\PathStart.jsx,
frontend\src\components\Job\BeforeSignup\UnlockPotential.jsx,
frontend\src\components\JobFeedPage\FilterButtons.jsx,
frontend\src\components\JobFeedPage\JobCard.jsx,
frontend\src\components\JobFeedPage\JobDetailCard.jsx,
frontend\src\components\Landing\Banner.jsx,
frontend\src\components\Landing\BestBuddy.jsx,
frontend\src\components\Landing\BestJob.jsx,
frontend\src\components\Landing\BestJob2.jsx,
frontend\src\components\Landing\BestJob3.jsx,
frontend\src\components\Landing\BestJob4.jsx,
frontend\src\components\Landing\Blog.jsx,
frontend\src\components\Landing\Collab.jsx,
frontend\src\components\Landing\Contact.jsx,
frontend\src\components\Landing\Hero.jsx,
frontend\src\components\Landing\Pricing.jsx,
frontend\src\components\Landing\UpcomingFeatures.jsx,
frontend\src\context\NavigationContext.jsx,
frontend\src\context\ProtectedRoute.jsx,
frontend\src\context\UserContext.jsx,
frontend\src\main.jsx,
frontend\src\pages\AboutPage.jsx,
frontend\src\pages\EducationPage.jsx,
frontend\src\pages\HomePage.jsx,
frontend\src\pages\JobFeedPage.jsx,
frontend\src\pages\JobPageAfter.jsx,
frontend\src\pages\JobPageBefore.jsx,
frontend\src\pages\JobPortalPage.jsx,
backend\dockerfile,
backend\docs\fonts\OpenSans-Bold-webfont.eot,
backend\docs\fonts\OpenSans-Bold-webfont.woff,
backend\docs\fonts\OpenSans-BoldItalic-webfont.eot,
backend\docs\fonts\OpenSans-BoldItalic-webfont.woff,
backend\docs\fonts\OpenSans-Italic-webfont.eot,
backend\docs\fonts\OpenSans-Italic-webfont.woff,
backend\docs\fonts\OpenSans-Light-webfont.eot,
backend\docs\fonts\OpenSans-Light-webfont.woff,
backend\docs\fonts\OpenSans-LightItalic-webfont.eot,
backend\docs\fonts\OpenSans-LightItalic-webfont.woff,
backend\docs\fonts\OpenSans-Regular-webfont.eot,
backend\docs\fonts\OpenSans-Regular-webfont.woff,
backend\docs\global.html,
backend\docs\index.html,
backend\docs\models_TextContent.js.html,
backend\docs\module-TextContent.html,
backend\docs\routes_textRoutes.js.html,
backend\docs\scripts\prettify\Apache-License-2.0.txt,
backend\docs\textRoutes.js.html,
backend\jsconfig.json,
backend\jsdoc.config.json,
backend\package-lock.json,
backend\package.json
```

**Notes**: Cache optimization required for other.

**[Feature] Implement MongoDB-Based Caching Strategy**

---

#### **Description:**
Implement a caching strategy for the project using **MongoDB** as the storage layer. This will optimize the performance of API calls, static asset serving, and data query operations. The caching strategy will cover the following categories:
1. **Frontend Static Assets**
2. **Frontend Dynamic Caching**
3. **Backend Static Assets**
4. **Backend Dynamic Caching**

---

#### **Tasks:**
1. **Setup MongoDB Cache Collection:**
   - Create a `cache` collection with the following schema:
     ```javascript
     {
       "key": "unique_cache_key",  // Unique identifier for the cached item
       "data": {...},             // Cached data (JSON, arrays, etc.)
       "createdAt": new Date(),   // Cache creation timestamp
       "expiresAt": new Date()    // Cache expiration timestamp
     }
     ```

2. **Implement Cache Middleware for Express APIs:**
   - Add a middleware for API routes to:
     - Check for existing cache in MongoDB.
     - Serve the cached response if available.
     - Save the response in MongoDB if not available, with an expiration time.

3. **Frontend Static Assets:**
   - Cache static files (e.g., CSS, JS, images) in MongoDB using GridFS.
   - Serve the assets via an Express route.

4. **Backend Dynamic Caching:**
   - Cache query results for frequently accessed database data in MongoDB.
   - Implement a helper function to manage cache:
     ```javascript
     const getCachedQueryResult = async (queryKey, queryFunction) => {
       const cachedResult = await Cache.findOne({ key: queryKey });
       if (cachedResult) {
         return cachedResult.data;
       }
       const freshResult = await queryFunction();
       await Cache.create({
         key: queryKey,
         data: freshResult,
         expiresAt: new Date(Date.now() + 1000 * 60 * 15) // Cache for 15 minutes
       });
       return freshResult;
     };
     ```

5. **Cache Invalidation:**
   - Use MongoDB TTL indexes for automatic expiration of cache entries:
     ```javascript
     db.cache.createIndex({ "expiresAt": 1 }, { expireAfterSeconds: 0 });
     ```
   - Set up manual or event-based invalidation for dynamic data.

6. **Analytics and Logging:**
   - Track cache hits and misses for analysis.
   - Log the following metrics:
     - Cache Key
     - Hit or Miss
     - Timestamp

---

#### **Acceptance Criteria:**
- [ ] MongoDB cache collection is created with TTL indexes.
- [ ] Middleware for API caching is functional and integrated.
- [ ] Frontend static assets are cached and served via MongoDB (GridFS).
- [ ] Backend query results are cached with proper expiration.
- [ ] Cache invalidation is implemented for dynamic data.
- [ ] Logs provide detailed metrics for cache performance.

### GitHub Task Template

**Title:** `[Feature] Implement In-Memory Caching Framework`

**Body:**

---

### Description

Implement an in-memory caching framework for the Express and MongoDB project. The caching should improve performance and reduce database load by storing frequently accessed data in memory. This implementation replaces Redis with a simpler `node-cache` solution.

---

### Tasks

1. **Install Dependencies**
   - Add `node-cache` to the project:
     ```bash
     npm install node-cache
     ```

2. **Setup Caching Logic**
   - Create a `cache` instance using `node-cache`.
   - Use `stdTTL` to set default expiration time (e.g., 10 minutes).
   - Use middleware to check the cache before querying the database.

3. **Implement Middleware**
   - Add a middleware function to handle cache hits and misses:
     - Check if data exists in the cache.
     - If found, return the cached response.
     - Otherwise, query the database and store the result in the cache.

4. **Add Cache Invalidation**
   - Invalidate relevant cache keys after data updates to ensure consistency.
   - Use `cache.flushAll()` for global cache invalidation.

5. **Integrate with Routes**
   - Apply the caching logic to API routes that fetch frequently accessed data.

6. **Optimize MongoDB Queries**
   - Add indexes to MongoDB collections for improved query performance:
     ```javascript
     mongoose.connection.once('open', () => {
         mongoose.connection.collection('collection_name').createIndex({ field_name: 1 });
     });
     ```

7. **Add HTTP Cache Control**
   - Use `Cache-Control` headers for static assets and API responses:
     ```javascript
     app.use((req, res, next) => {
         res.set('Cache-Control', 'public, max-age=600');
         next();
     });
     ```

8. **Testing**
   - Write unit tests to ensure:
     - Cache hits return correct data.
     - Cache misses query the database and update the cache.
   - Use tools like Postman or `curl` to manually test response times.

---

### Resources

- [[node-cache Documentation](https://www.npmjs.com/package/node-cache)](https://www.npmjs.com/package/node-cache)
- [[Express.js Official Docs](https://expressjs.com/)](https://expressjs.com/)
- [[Mongoose Official Docs](https://mongoosejs.com/)](https://mongoosejs.com/)

---
### Acceptance Criteria

- [ ] Cache middleware integrated and functional.
- [ ] Cache invalidation implemented on updates.
- [ ] MongoDB indexes created for optimized queries.
- [ ] Routes tested for both cache hits and misses.
